# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: mutation-testing
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'
      - '.gitignore'
concurrency:
  group: ${{ github.ref }}-mutants
  cancel-in-progress: true
jobs:
  mutants:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-mutants
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-mutants
      - name: Run mutation tests
        run: cargo mutants --no-shuffle --shard 1/4
      - name: Upload mutants.out directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-report
          path: mutants.out/